os: windows
language: node_js
node_js:
- 18
before_install:
  - npm i -g npm@8.19.3
install:
- npm ci
deploy:
  provider: heroku
  skip_cleanup: true
  strategy: git
  api_key:
    secure: kp8v4TkRmi/oINCva6ui59ip8TbETw1bMkWvziYD0759aHD4A71zGX/sSsQuYTst0i4m2/gbs5jov4jKfS4/2IEddGhEHLEzwSbmx3fxLSt00/G1N6UiDR341gEPAzpZGdB739VAuNw7vD00MMh47q/F31qsosk97UeJLppuEN7xwccS1sH+6VkPq64UAr19dw3tw1GBrMHgRfaHYsH1LlLyd354AyTeoSfMI+y3qKbUCLB0DXcfICwPF5GYTzPizshs+YAcY9NnAwMeqKZ4wzO9xQ08E+xo7a1LlOdV4o3RAYzdNpS2vSZFXwMf/DoKW5IEX59CLYqb25zQKxLnxDfnd4uBWRHhHQXHwVaKfszEpHGi3cui+0QRnYU1stGIPtqbfaj0gTXa/h+gqMloB/uzs/oQzTxguOe9BxpQD5GuMtJOJmmBELIgPNxoE9ov4GdROoT20g6qt/1XSM4g5ievtBOMAm042Ueio/imneWSsrJkGbmvFQGwBP90IWy/qbyKfSK+svJnaHWH655ZzER8GqG4oqS1cgVXlmpSv8qtnQxJJsg39skvD0lSvcCU+hMtv9L3/UijuTDW3KrJoev1ZJd/XNH6uCR8fipuFu7JtTwiADtRrap22/y8ZMp4FpxxGsVFKzoEWJm3T4NIJPSujnhBDT7tOo5ZaGNZZ8M=
  app:
    main: comp3006-app
cache: npm