os: windows
language: node_js
node_js:
- 18
before_install:
- npm i -g npm@8.19.3
install:
- npm ci
deploy:
  provider: heroku
  skip_cleanup: true
  strategy: git
  api_key:
    secure: GNfl0l8wrULbWyAdZhp/9nSZ/Rk4Ve7+vkfAKa7QU+D8Q8gYSZlhxZtZxz1anLpJ+x8lRIqAmJCa0hkwSd4kL+JfHlPr8FLpiJ05k8kaDaxFm78Xm4aQp09SEGW7JghQuyob34A9DpYfs+C/Wv6QG2gESdWGkgeMTRwz3DSNIe0jMLI3wi2VeADZBVfC1J1Luo0MzE89ODPmK9XGs9ehQmt6iyOvZltfVircRieOlwnXpWMsXMmKqYhzUZ0Bk+PBoQlPv+rmT/B6FTzZaFyuKSSf1WIbxJyYRFhupCfHUb+qCCz/t5GbX67XpZM6xJdZuI9VUtglyzzool+Tqe/qASvLf85xzEIcOzuFVMs1WQW461Ce7YE1BUhcX8XZ1YWfgk4lt9ALy++haphRpuO0+wYeSq7lPtErhKY2iKoq7ZMQltKDmDGr2KTLEwQhtfjrvc442RbVE1rX01cXFQJHE2mwUrRthC+zlFXHfkrxQiyy3JSvgfvVr1u1Efmwsmxoe3aR3usY64APQBLB0lax3dsj8N1bN4YydY+hY6EfiTvYhE+uPR17uUI8p0w4PcFEbBH0BE9ApdcMZCbdOE0KlbiCjrkDl3/Hf3EDz2d6X7eqB6itqGWVGiJH0CwvImmOuM76EWapi5kaKsOqMK+SCQZW1dqHbREcdIQrMYwvvFg=
  app:
    main: comp3006-app
cache: npm
